apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-bj6s
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-bj6s@sha256:b0bb7436c83f486f472930496486637fa3a615c49853820a36ed2a452af15308
        name: my-nodejs
        resources: {}
status: {}
